import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <head></head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}
      >
        <div className="min-h-screen grid grid-rows-[auto_1fr]">
          <nav className="flex items-center justify-between gap-4 py-4 px-12 absolute top-0 left-0 right-0">
            <Link href="/" className="text-2xl font-bold">MorphyusAI</Link>
            <Link href="/login">Login</Link>
          </nav>
          {children}
        </div>
      </body>
    </html>
  );
}
